### ISSUE TITLE
Url shortner 

### ISSUE THREAD

**Issue by KnowWolf** [MrDemonWolf/share#194]
# 🚀 feature request

### Description
Add the ability to use sharex url shortener to the share script. 

### Describe the solution you'd like
Add sharex url shortener option to the panel with options to see how many times the link has been clicked and the ability to rename the code at the end so you can create s.example.com/social ect

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by nathanhenniges** [comment]
Added in #225
