### ISSUE TITLE
SendGrid Error

### ISSUE THREAD

**Issue by notkyoyo** [MrDemonWolf/share#256]
# 🐞 bug report

### Affected Package

 The issue is caused by @sendgrid/mail
 

### Is this a regression?

 I'm not sure, but I believe yes.

### Description

 I'm not receiving any emails from SendGrid.

## 🔥 Exception or Error
<pre>
<code>

[App] ResponseError: Bad Request
[App]     at C:\Users\User\Desktop\share\node_modules\@sendgrid\client\src\classes\client.js:146:29
[App]     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
[App]   code: 400,
[App]   response: {
[App]     headers: {
[App]       server: 'nginx',
[App]       date: 'Sat, 13 Feb 2021 11:11:25 GMT',
[App]       'content-type': 'application/json',
[App]       'content-length': '80',
[App]       connection: 'close',
[App]       'access-control-allow-origin': 'https://sendgrid.api-docs.io',
[App]       'access-control-allow-methods': 'POST',
[App]       'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
[App]       'access-control-max-age': '600',
[App]       'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
[App]     },
[App]     body: { errors: [Array] }
[App]   }
[App] }
</code></pre>

## 🌍  Your Environment

**NodeJS Version:**
<pre><code>

v14.15.4
</code></pre>

**Anything else relevant?**

**Comment by nathanhenniges** [comment]
Could you try running the new master branch?  See if upgrading it fixed.

**Comment by notkyoyo** [comment]
sure
