### ISSUE TITLE
[Feature Request] Log IP w/ request, IP Ban

### ISSUE THREAD

**Issue by BitwiseMLP** [MrDemonWolf/share#55]
I was wondering if it were possible to add IP logging per request. Like for example:
GET / 10ms 127.0.0.1 (I cant remember the exact format in which those are displayed.)
As well as adding a separate option to just ban a specific IP to help block malicious users.

**Comment by nathanhenniges** [comment]
Thanks for the feature request.  Already was adding a way to ban people but forgot that big one which was to IP ban a user as that could help a lot.  For logging the IP with the request, not a bad idea.  Going to try to add all this in version 4.
Version 4 will be released hopefully soon which is a big overhaul update.  Have to make an upgrader or people may have to reinstall which is not the biggest deal but don't want that.

Thanks again for the feature request.

**Comment by BitwiseMLP** [comment]
Another feature that came into my mind text rendering.
https://github.com/TannerReynolds/ShareX-Upload-Server
Like when you would upload a text file instead of rendering it as just a raw text file it would use something like this: http://155.138.230.9/SSuaQ (the above github link leads to where I pulled this from)
-
Video support would be neat too, like instead of just being a download the video would be available to watch from the site or from something like Discord embed

**Comment by nathanhenniges** [comment]
Thanks for this information. Their app looks really good.  I can try adding stuff like that to my app.   If you don't mind you can join my discord [here](https://l.demonwolf.dev/discord)

**Comment by nathanhenniges** [comment]
Sorry for the late adding of this.  Been busy with work.  Will get version 4 released ASAP.

**Comment by nathanhenniges** [comment]
Version 4 has been released.
