### ISSUE TITLE
feature_front-end-vaildater

### ISSUE THREAD

**Issue by nathanhenniges** [MrDemonWolf/share#70]
Add support for front-end validation.  Using https://www.npmjs.com/package/validator 

To pages/forms

-` /src/views/auth/login.ejs`
-` /src/views/auth/signup.ejs`
-`/src/views/admin/users/edit.ejs`
-`/src/views/admin/users/new.ejs`

**Comment by stmoerman** [comment]
Mind if I take this one?

**Comment by nathanhenniges** [comment]
> Mind if I take this one?

Sure thing.

**Comment by nathanhenniges** [comment]
Updated the Issue above but also wanted to add that I wanted to validate that an email is an email and password is at least 8 characters.   Hopefully, this helps.

**Comment by nathanhenniges** [comment]
This is open to anyone who wants to add this to the project.

**Comment by nathanhenniges** [comment]
This will not be added anymore.
