### ISSUE TITLE
feature_dark-mode

### ISSUE THREAD

**Issue by nathanhenniges** [MrDemonWolf/share#74]
Add dark mode feel to the web GUI of the APP.  Need's to have a setting toggle in account settings or dropdown if you want to try that.  

It should be both saved in the database and local storage so if they get logged out it can apply the theme still.

It is based on bootstrap.

Updated: Here's the setup [link](https://github.com/MrDemonWolf/share-mrdemonwolf-me/blob/master/SETUP.md) 

It may say in SETUP installer but that has not been added yet.

**Comment by cyh0968** [comment]
Your project sounds interesting! I will try that part!

**Comment by nathanhenniges** [comment]
I wanted to check up @cyh0968 . Are you having issues or need help?

**Comment by nathanhenniges** [comment]
This is now open back up to anyone who wants's to take on this.

**Comment by nathanhenniges** [comment]
Closing this.  As this may or may not be added later on.
